### ISSUE TITLE
Deactivated service: 404 Service Not Found

### ISSUE THREAD

**Issue by anxstj** [python-gitlab/python-gitlab#1557] opened 2021-07-28 13:23 UTC
## Description of the problem, including code/CLI snippet

Deactivated services are not found. This seems to be a problem since Gitlab version 13.12.x

```
#!/usr/bin/env python

import gitlab

gl = gitlab.Gitlab('https://gitlab.example.com', private_token='abc123', ssl_verify=True)
gl.auth()
real_project = gl.projects.get(674)
service = real_project.services.get('mattermost')
print(service)
setattr(service, "active", True)
service.save()
```

Without the service object, the service can't be activated. I don't see any possibility of working around this problem.

Edit: This happens only on new projects. As soon as the service was activated once (and deactivated later) `get()` will still return the object.

## Expected Behavior
`real_project.services.get('mattermost')` should return a service object which shows the service as deactivated.

## Actual Behavior
```
Traceback (most recent call last):
  File "/tmp/env/lib/python3.9/site-packages/gitlab/exceptions.py", line 304, in wrapped_f
    return f(*args, **kwargs)
  File "/tmp/env/lib/python3.9/site-packages/gitlab/mixins.py", line 112, in get
    server_data = self.gitlab.http_get(path, **kwargs)
  File "/tmp/env/lib/python3.9/site-packages/gitlab/client.py", line 662, in http_get
    result = self.http_request(
  File "/tmp/env/lib/python3.9/site-packages/gitlab/client.py", line 628, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Service Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/./test.py", line 10, in <module>
    service = real_project.services.get('mattermost')
  File "/tmp/env/lib/python3.9/site-packages/gitlab/v4/objects/services.py", line 273, in get
    obj = super(ProjectServiceManager, self).get(id, **kwargs)
  File "/tmp/env/lib/python3.9/site-packages/gitlab/exceptions.py", line 306, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Service Not Found
```

## Specifications

  - python-gitlab version: 2.10.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.1.0

**Comment by JohnVillalovos** [comment] 2021-07-28 15:52
Since Gitlab changed their API, I think you will need to `list` the services first. You can no longer assume that a service is there.

https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-services

**Comment by anxstj** [comment] 2021-07-28 18:31
That's not the case here. I need to activate a, per default, disabled service. Therefore I need to retrieve the service object for that particular service. And that's not possible.

**Comment by JohnVillalovos** [comment] 2021-07-29 00:38
Okay. I'm not sure about this and haven't tried it. But I was looking at the code.

Maybe something like this will work
```
real_project = gl.projects.get(674)
real_project.services.update(id="mattermost", new_data={"webhook": "SOME_URL"})
```

Note: https://docs.gitlab.com/ce/api/services.html#mattermost-notifications

**Comment by anxstj** [comment] 2021-07-29 06:58
Thanks that did the trick.

It would be nice if the documentation would cover this new behavior.

**Comment by JohnVillalovos** [comment] 2021-07-29 17:42
> Thanks that did the trick.

Great!

> It would be nice if the documentation would cover this new behavior.

If you would like to do a Pull Request to update the docs it would be appreciated. Thanks.

**Comment by gdubicki** [comment] 2021-08-07 12:55
Isn't this a duplicate of #1523?

**Comment by nejch** [comment] 2022-06-24 16:22
Thanks @gdubicki, it is!

Also we can do:

```python
mattermost = project.services.get("mattermost", lazy=True)
mattermost.webhook = "http://mattermost_host/hooks/blabla"
mattermost.save()
```

**Closed by nejch** 2022-06-24 16:22 UTC
