### ISSUE TITLE
Incorrect Exception thrown when job artifact not found.

### ISSUE THREAD

**Issue by tmos22** [python-gitlab/python-gitlab#1186] opened 2020-09-11 13:16 UTC
## Description of the problem, including code/CLI snippet
While testing an internal upgrade from 12.x to 13.x, there is a discrepancy in the `Exception` raised when trying to pull job artifacts that do not exist with `ProjectJobObject.artifact("artifact-name")`. Verified the issue by running against gitlab.com.

Running against our local 12.x instance properly throws the `gitlab.exceptions.GitlabGetError: 404`

## Expected Behavior
The library should throw a `gitlab.exceptions.GitlabGetError 404`

```python
>>> prjJob.artifact("test.txt")
Traceback (most recent call last):
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/exceptions.py", line 271, in wrapped_f
    return f(*args, **kwargs)
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/v4/objects.py", line 1950, in artifact
    path, streamed=streamed, raw=True, **kwargs
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/__init__.py", line 598, in http_get
    "get", path, query_data=query_data, streamed=streamed, **kwargs
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/__init__.py", line 573, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 page not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/cli.py", line 43, in wrapped_f
    return f(*args, **kwargs)
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/exceptions.py", line 273, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabGetError: 404: 404 page not found

```

## Actual Behavior
```python
>>> real = gitlab.Gitlab("https://gitlab.com", "REDACTED")
>>> prj = real.projects.get("tmos22/test-project")
>>> prjJob = prj.jobs.list()[0]
>>> prjJob.artifact("potato.txt")
b'this is a test 188812022\n'
>>> prjJob.artifact("test.txt")
Traceback (most recent call last):
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/cli.py", line 42, in wrapped_f
    return f(*args, **kwargs)
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/exceptions.py", line 279, in wrapped_f
    return f(*args, **kwargs)
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/v4/objects/__init__.py", line 2142, in artifact
    path, streamed=streamed, raw=True, **kwargs
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/__init__.py", line 593, in http_get
    "get", path, query_data=query_data, streamed=streamed, **kwargs
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/gitlab/__init__.py", line 531, in http_request
    result = self.session.send(prepped, timeout=timeout, **settings)
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/root/.config/py-virtualenvs/ccupgrade/lib64/python3.6/site-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

## Specifications

  - python-gitlab version: 2.5.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by nejch** [comment] 2020-09-12 12:02
This is an upstream bug that can be reproduced with curl. Most likely introduced here I'd say, especially as you say it comes with 13.x:
https://gitlab.com/gitlab-org/gitlab/-/commit/166b93070752869af58427a79000999fcc8f0f6d#4161e2c880e1975dc06c0a6aa1c6d01685dc960c_76_76

curl output:
```bash
curl -H 'Private-Token: [redacted]' https://gitlab.com/api/v4/projects/[redacted]/jobs/[redacted]/artifacts/nonexistent
404 page not found
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

Could you open an issue on GitLab instead?

**Comment by tmaas22** [comment] 2020-09-13 02:15
What environment are you running `curl` on? While I was testing with our 2 internal gitlab instances, the curl commands showed no differences between their outputs.

**Comment by nejch** [comment] 2020-09-13 15:25
Hmm, I might need to take that back, but I get the above error against GitLab.com on both Linux (curl 7.58.0) and Windows (curl 7.64.0). But not with curl 7.68.0 from the `ubuntu:latest` docker image. Probably because of this change in 7.65 https://github.com/curl/curl/commit/2e5ceb3934a7bc5422c5a3a18daafa1b1af02090

If you `enable_debug()`, I think you'll see that GitLab is not sending the same headers (`Transfer-Encoding` is set to `chunked`) for 404 only at this endpoint, is that right? Was that different on 12.x? Because it seems there's a chain of issues on this from requests https://github.com/psf/requests/issues/4248 to urllib3 https://github.com/urllib3/urllib3/issues/1516, basically "server is saying response is chunked but it isn't. Should the client handle this?" The latest urllib3 will just raise a new type of exception. 

```
# Other endpoints give json 404. e.g. invalid job
>>> project.jobs.get(123546)
...
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Sun, 13 Sep 2020 13:33:23 GMT
header: Content-Type: application/json
header: Content-Length: 27
header: Connection: keep-alive
header: Cache-Control: no-cache
header: Vary: Origin
....
```
```
# Valid job, invalid artifact
>>> job.artifact('test.txt')
...
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Sun, 13 Sep 2020 13:56:35 GMT
header: Content-Type: text/plain; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: Cache-Control: max-age=0, private, must-revalidate
...
```

It also seems like this is affected by how the reverse proxy in front of GitLab handles 404 responses.
I actually can't reproduce your issue on my company's instance (13.3.5 CE) where the proxy does 404 slightly differently. I get a `GitlabGetError` even with your example above.

**Comment by tmaas22** [comment] 2020-09-14 13:55
I'm stuck on `curl` 7.29, which explains not seeing much of differences.

Looks like the the headers for gitlab were different in `12.x` for the artifact endpoint.

```python
>>> job.artifact("test.txt")
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Date: Mon, 14 Sep 2020 13:38:21 GMT
header: Content-Type: application/json
header: Content-Length: 27
header: Connection: keep-alive
header: Cache-Control: no-cache
header: Vary: Origin
```

I'd be interested to see your reverse proxy configuration to see why you aren't able to see this issue.

**Comment by nejch** [comment] 2020-09-14 18:53
Sorry I don't have access to that config, but I always get a proper HTML response from nginx for 404 for both browsers and API calls, which is probably why it's handled correctly by clients.
```
reply: 'HTTP/1.1 404 Not Found\r\n'
header: Server: nginx
header: Date: Mon, 14 Sep 2020 18:37:50 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
```

I'd still say this is an upstream issue considering the change in response, I can also try and open an issue on gitlab.com later. there's a mini-novel of logs already here 😁

**Comment by max-wittig** [comment] 2020-09-15 06:04
Looks like a GitLab.com only thing again to me, same with their rate-limiting headers.

**Comment by nejch** [comment] 2022-06-24 16:29
Since we were able to reproduce this error with curl, I'd say let's close this for now and if anyone finds this in the future please ping us again if you have any better ideas :) Thanks for the report @tmos22.

**Closed by nejch** 2022-06-24 16:29 UTC
Labels: upstream
