### ISSUE TITLE
"organization" and "location" fields are not set by users.create()

### ISSUE THREAD

**Issue by boileaum** [python-gitlab/python-gitlab#264] opened 2017-05-20 08:48 UTC
if `'location'` and `'organization'` arguments are passed to `users.create()` method, it results in empty fields in the new user's profile.  
However, using  
```
user.organization = "My org"
user.location = "My loc"
user.save()
```
after creating the user, these fields are actually filled.

**Comment by gpocentek** [comment] 2017-05-24 06:45
Hi,

I've not been able to reproduce the problem. I created a user with both attributes and it worked as expected. What version of the gitlab server are you running?

**Comment by boileaum** [comment] 2017-06-02 12:14
I am currently running GitLab 9.2.2. The problem was the same with GitLab 9.1.2. I'm using python-gitlab 0.20.

**Comment by boileaum** [comment] 2017-06-02 12:59
Same behaviour with python-gitlab 0.21.1.

**Comment by gpocentek** [comment] 2017-06-02 13:38
Thanks for your feedback.

Did you get a chance to test with the v4 API? It's still young in python-gitlab but it might help. See 'GitLab v4 support' in http://python-gitlab.readthedocs.io/en/stable/api-usage.html#gitlab-gitlab-class

**Comment by boileaum** [comment] 2017-06-02 14:36
Thanks to you!  
API v4 works but still has the same problem.

**Comment by gpocentek** [comment] 2017-08-05 05:59
Are you still facing this issue? Did you get a chance to test with a newer version of Gitlab maybe?

**Comment by boileaum** [comment] 2017-08-17 13:13
I'm still facing this issue with GitLab 9.3.9, API version 4 and python-gitlab 0.21.2. If I run: 
```python
import gitlab

gl = gitlab.Gitlab.from_config()
print('API version:', gl.api_version)
userdict = {'username': 'wayne',
            'name': 'Bruce Wayne',
            'email': 'bruce.wayne@wayne-entreprises.com',
            'organization': 'Wayne Entreprises',
            'location': 'Gotham City',
            'reset_password': True}
gluser = gl.users.create(userdict)
print('email:', gluser.email)
print('organization:', gluser.organization)
print('location:', gluser.location)
```
I get:
```
API version: 4
email: bruce.wayne@wayne-entreprises.com
organization: None
location: None
```
and organization and location are still empty in the user profile.
I will try again with a newer version of GitLab as soon as I perform the upgrade. Do you confirm that you do not reproduce the issue using the code above?

**Comment by boileaum** [comment] 2017-08-18 13:45
Same problem with GitLab 9.4.5, API version 3 or 4.

**Comment by gpocentek** [comment] 2017-09-10 07:18
Hi @boileaum

I've been able to reproduce the problem with your code sample with gitlab 9.5.2. Updating the object works as well.

I tested with curl and got the same result, so this seems to be a GitLab issue. Bug report here: https://gitlab.com/gitlab-org/gitlab-ce/issues/37675

**Comment by boileaum** [comment] 2017-09-13 08:37
Thank you! I will follow this issue.

**Comment by gpocentek** [comment] 2018-05-19 06:54
I'm closing this issue as I believe it will solve itself once GitLab has released a fix. Feel free to reopen if needed.

**Closed by gpocentek** 2018-05-19 06:54 UTC
Labels: upstream
