### ISSUE TITLE
Bug: List all projects of current user returns empty list

### ISSUE THREAD

**Issue by Malaber** [python-gitlab/python-gitlab#2827] opened 2024-03-22 12:39 UTC
## Description of the problem, including code/CLI snippet

I want to call `gitlab_client.projects.list(membership=True, all=True)` and have all projects returned that the current user is a member of.

## Expected Behavior
Returns a list of projects the user is a member of.
Can be filtered via the gitlab API using the `membership` parameter.
https://docs.gitlab.com/ee/api/projects.html#list-all-projects

## Actual Behavior
Returns an empty list

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Enterprise Edition [v16.9.2-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.9.2-ee)

**Comment by nejch** [comment] 2024-06-06 20:36
@Malaber I just checked and verified that the client does pass the right parameters (see below with debug output).

So I'd say the issue is somewhere in how you provide the token or the token itself (with no auth, it will always be an empty list). Make sure you really supply a token that has some projects.

```
Python 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl = gitlab.Gitlab()
>>> gl.enable_debug()
>>> gl.projects.list(membership=True, all=True)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gitlab.com:443
DEBUG:http.client:send: b'GET /api/v4/projects?membership=True HTTP/1.1\r\nHost: gitlab.com\r\nUser-Agent: python-gitlab/4.6.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-type: application/json\r\n\r\n'
DEBUG:http.client:reply: 'HTTP/1.1 200 OK\r\n'
```

I'll close this but feel free to reopen if you still get issues after fixing the auth.

**Closed by nejch** 2024-06-06 20:36 UTC
