### ISSUE TITLE
Read snippet content from stdin

### ISSUE THREAD

**Issue by tclh123** [python-gitlab/python-gitlab#1002] opened 2020-01-27 11:59 UTC
related https://github.com/python-gitlab/python-gitlab/issues/700

**Comment by tclh123** [comment] 2020-01-27 12:24
Just create a wrapper script https://gist.github.com/tclh123/4ccb504839ad40229edfce2ef326ac92. In case someone need it.

**Comment by max-wittig** [comment] 2020-01-27 14:24
@tclh123 Thanks for the update. I would say we close this as a duplicate of #700

**Closed by max-wittig** 2020-01-27 14:24 UTC
