### ISSUE TITLE
Wiki subpage moved up when updated

### ISSUE THREAD

**Issue by trotro** [python-gitlab/python-gitlab#2706] opened 2023-10-26 16:40 UTC
## Description of the problem, including code/CLI snippet

Hi, I'm using the libraire inside a Python script and when I saving a wiki subpage, it is moved up.

```python
gwuc_page: ProjectWiki = glp.wikis.get('my/slug')
# do some work
gwuc_page.save()
```

## Expected Behavior

The page is saved.

## Actual Behavior

The page is saved and moved to 'slug' instead of 'my/slug'

## Specifications

  - python-gitlab version: 3.15.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): on-premise GitLab Enterprise Edition v16.2.8-ee

**Comment by nejch** [comment] 2023-11-17 09:38
@trotro I can't quite reproduce your issue, but I can see that changing the title of the wiki affects the slug after calling the `PUT` request. So I assume this is just how the GitLab API works and it's a bit tricky to work with `save()` here as the identifying attribute itself potentially changes over the lifetime of the object. It might make more sense to work with `.update()` directly on the manager in this case.

Can you give me an exact reproduction code snippet?

**Comment by Val06D** [comment] 2023-11-21 07:36
Hi, I'm having the same problem as above.

```
 def write_to_gitlab_wiki(json_file_name):
    # read json file
    with open(json_file_name, 'r') as f:
        data = json.load(f)

    # Connect with Gitlab Wiki
    gl = gitlab.Gitlab(url='https://gitlab.XXXX.XXXX', private_token='XXXXXX')
    gl.auth()

    # Create project link
    project = gl.projects.get(XX)

    # write selected fields inside wikis

    title_page = './home/Functions'
    content = ''

    for record in data:
            title_issue = record['title']
            description = record['description']
            content += f'\n\n# {title_issue}\n\n{description}'

    try:
        page = project.wikis.get(title_page)   # Take informations for the Functions page of the current project
    except gitlab.exceptions.GitlabGetError as e:

        project.wikis.create({'title': title_page, 'content': content})

        raise SystemExit

    page.content = content
    print(page) # here, the slug is home/Functions correctly
    page.save()
    print(page) # here the slug changes in Functions
    print("Page updated.")
```

I'm pretty new so I don't understand your suggestion about the .update() with the manager. I didn't come up with a solution in the documentation. Thank you in advance for your time.

**Comment by nejch** [comment] 2023-11-23 14:35
@trotro @Val06D thanks, I can reproduce this now even with curl, see below. This will move the page and return the top-level slug:

```
nejc@fedora ~]$ curl --data "content=test with put" -X PUT -H "private-token: $GITLAB_TOKEN" https://gitlab.example.com/api/v4/projects/nejc%2Frepro-playground/wikis/subdir%2FNew-Title
{"format":"markdown","slug":"New-title","title":"New title","content":"test with put","encoding":"UTF-8"}
```

So unfortunately not a python-gitlab issue but maybe a regression in GitLab's API if it's a new bug, or perhaps it's always been the behavior. Could you open an issue in https://gitlab.com/gitlab-org/gitlab instead please? Feel free to link it here for other people who might stumble across the same thing.

**Comment by Val06D** [comment] 2023-11-24 09:50
Done here https://gitlab.com/gitlab-org/gitlab/-/issues/432850.

**Comment by nejch** [comment] 2023-11-28 22:10
I'll close this one here since we fully depend on an upstream fix but I'm subscribed there and in case we need to adjust after they fix it, we can revisit this here. But hopefully only the upstream fix is needed to make this work as expected.

**Closed by nejch** 2023-11-28 22:10 UTC
Labels: upstream
