### ISSUE TITLE
Retrieving registered runners via cli does not work

### ISSUE THREAD

**Issue by kaosmonk** [python-gitlab/python-gitlab#1656] opened 2021-10-29 17:32 UTC
## Description of the problem, including code/CLI snippet
Issue is with listing runners when using cli, do not seem to be able to list them at all as an empty list is returned each and every time I run one of the following
```
$ gitlab -o json -c /path/to/config/file runner list
[]
$ gitlab -o json -c /path/to/config/file runner list --all
[]
```
I'm the admin and am using a personal token that has all the access privileges. Any other cmd I tried out returns expected and desired result but when listing runners.
I've tried by supplying a different output, scope, tag-list, page and per-page arguments to no avail. Result is always an empty list.
I can list and manage runners when going through API with curl and/or `gitlab` package and the same token. Only cli does not seem to work at all.
I've turned on debugging and have noticed that the API endpoint being hit is `/api/v4/runners` but it should be `/api/v4/runners/all` instead. ANd pagination should be obeyed as well so that all runners could be returned and not just first 100.

If I try something like:
```
$ gitlab -o json -c /path/to/config/file runner all --id $id
```
I always get 20 runners with a completely different ID than the one I specified to a `--id` arg. These 20 runners are always the same ones no matter what ID I specify. Is that a pagination issue? It turned out that this particular cmd is trying to hit the `/api/v4/runners/all?id=$id` API.

## Expected Behavior
List all the runners registered with the gitlab server instance and be able to retrieve _full_ information on all the currently registered runners.

## Actual Behavior
No result is return at all.

## Specifications

  - python-gitlab version: 2.10.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 14.4.1 (self hosted)

**Comment by nejch** [comment] 2022-01-13 20:19
Hi @kaosmonk, this issue is valid but I'll close it as a duplicate of https://github.com/python-gitlab/python-gitlab/issues/593 where you will find similar discussions.

We'll fix this by adding an extra `runner-all list` command which will hit the right endpoint and  handle pagination properly.

**Closed** 2022-01-13 20:20 UTC
Labels: cli
