### ISSUE TITLE
job.refresh() doesn't exist but is needed (hacky fix included)

### ISSUE THREAD

**Issue by 1ace** [python-gitlab/python-gitlab#2783] opened 2024-02-04 16:43 UTC
## Description of the problem, including code/CLI snippet

When finding a manual job in a pipeline and deciding to `.play()` it (through `project.jobs.get(pipeline_job.id).play()` since `.play()` is not supported on pipeline jobs), the pipeline job status doesn't get updated.

One would think we might need to call `pipelin_job.refresh()` to get the updated status, but this crashes instead, as the method doesn't exist on jobs.

## Expected Behavior

`job.refresh()` refreshes the job data, just like `pipeline.refresh()` does.

## Actual Behavior

```
  File ".../gitlab/base.py", line 134, in __getattr__
    raise AttributeError(message) from exc
AttributeError: 'ProjectPipelineJob' object has no attribute 'refresh'
```

## Specifications

  - python-gitlab version: 4.4.0
  - API version you are using (v3/v4): v4 (but not relevant for this issue)
  - Gitlab server version (or gitlab.com): 16.8.1 (but not relevant for this issue)

---

Looks like `ProjectPipelineJob` is missing the `RefreshMixin`, but just adding it doesn't work; `refresh()` does a `self.manager.gitlab.http_get()` with an incorrect path, and gets a 404 in return.
The path used is `/projects/{project_id}/pipelines/{pipeline_id}/jobs/{job_id}` but should be `/projects/{project_id}/jobs/{job_id}`.

The following crude patch fixes this issue, but someone who understand the `python-gitlab` codebase better than me should be able to fix this cleanly instead :slightly_smiling_face:
```patch
diff --git a/gitlab/mixins.py b/gitlab/mixins.py
index a232c31e31d88e0eadbe..9b0eb414a879aef99c46 100644
--- a/gitlab/mixins.py
+++ b/gitlab/mixins.py
@@ -186,6 +186,9 @@ def refresh(self, **kwargs: Any) -> None:
             if TYPE_CHECKING:
                 assert self.manager.path is not None
             path = self.manager.path
+        if '/pipelines/' in path and '/jobs/' in path:
+            import re
+            path = re.sub(r'/pipelines/\d+', '', path)
         server_data = self.manager.gitlab.http_get(path, **kwargs)
         if TYPE_CHECKING:
             assert not isinstance(server_data, requests.Response)
diff --git a/gitlab/v4/objects/pipelines.py b/gitlab/v4/objects/pipelines.py
index 75306119b255c471611c..51ad470791ab3c032132 100644
--- a/gitlab/v4/objects/pipelines.py
+++ b/gitlab/v4/objects/pipelines.py
@@ -140,7 +140,7 @@ def create(
         )
 
 
-class ProjectPipelineJob(RESTObject):
+class ProjectPipelineJob(RefreshMixin, RESTObject):
     pass
 
 
```

**Comment by 1ace** [comment] 2024-02-04 17:28
While trying to understand the code to find a better fix for the above, I noticed that `ProjectJob`'s `.play()` also doesn't update the job status; https://github.com/python-gitlab/python-gitlab/pull/2784 fixes that

**Comment by 1ace** [comment] 2024-02-04 18:17
I don't understand why `ProjectPipelineJob` exists though; why doesn't `ProjectPipelineManager.list()` return a list of `ProjectJob`?
That would resolve a bunch of limitations, and I don't see the downside/blocker for doing that, so I must be missing something :sweat_smile:

**Comment by nejch** [comment] 2024-02-05 05:49
@1ace they're different objects because they're created from different endpoints, and don't necessarily have the same amount of details returned. We sort of follow the REST API path segment structure for the most part with this approach. We also document this a bit:

![image](https://github.com/python-gitlab/python-gitlab/assets/16777978/47c67ee4-26c9-4879-b0dc-3902721cf1b2)

This is far from the only case, so if we wanted to be consistent here, we would have to add this path hack to almost every endpoint where similar-but-not-quite-the-same resources are returned. This is why for now we simply document how to get an editable resource when fetched from a different endpoint:

https://python-gitlab.readthedocs.io/en/stable/faq.html#i-cannot-edit-the-merge-request-issue-i-ve-just-retrieved

However, if `refresh()` is needed for `ProjectJob` we should be able to add that.

**Comment by nejch** [comment] 2024-02-10 16:31
@1ace with #2784 merged, does this cover your use case along with the docs above?

**Comment by nejch** [comment] 2024-06-06 20:50
I'd say as long as we tie our resources to the API paths the difference in project / pipeline jobs is expected behavior, so I'll go ahead and close this as #2784 should now return the job endpoint payload.

**Closed by nejch** 2024-06-06 20:50 UTC
Labels: enhancement, docs
