### ISSUE TITLE
gitlab.projects isn't known by python-gitlab

### ISSUE THREAD

**Issue by KameKam** [python-gitlab/python-gitlab#1493] opened 2021-06-02 23:21 UTC
## Description of the problem, including code/CLI snippet
edit : I've tried already with projects and project terms :) 
Hello 
I've an issue that I don't understand. I use the official documentation to use project from python-gitlab library. All others modules work but project isn't know by gitlab,find bellow my code 
main.py : 

```
import gitlab as gl
import pandas as ps
import time
subg_applications_id =''
appname=''
env=''
rg=''
net=''
csv_f = ps.read_csv('rg.csv', header=None)
root_parent_id = 115
project_model_id = 282
gitl = gl.Gitlab.from_config('pvcp', ['./.python-gitlab.cfg'])

def create_project(app_group_id):
    app_group=gitl.groups.get(app_group_id)
    if app_group.subgroups.list(search='Spoke'):
        print("Project Spoke already exists in application group", app_group[-1].name , " , nothing done")
        return(False)
    else:
        p = gl.project.get(project_model_id)
        export = p.exports.create()
        # Wait for the 'finished' status
        export.refresh()
        while export.export_status != 'finished':
            time.sleep(1)
            export.refresh()
        # Download the result
        with open('./export.tgz', 'wb') as f:
            export.download(streamed=True, action=f.write) 
        output = gl.projects.import_project(open('./export.tgz', 'rb'), namespace=app_group_id)
        # Get a ProjectImport object to track the import status
        project_import = gl.projects.get(output['id'], lazy=True).imports.get()
        while project_import.import_status != 'finished':
            time.sleep(1)
            project_import.refresh()   
        spoke_id=app_group.list(search='Spoke')[-1].id
        return spoke_id
```
## Expected Behavior
 get projects found but gitlab library

## Actual Behavior
PS C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab> .\main.py
Start creation of  elk
Sub already exists
applications group exists,go to  elk  application's creation folder
Nothing to do all folder exists
Traceback (most recent call last):
  File "C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab\main.py", line 103, in <module>
    main()
  File "C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab\main.py", line 100, in main
    spoke_id=create_project(app_id)
  File "C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab\main.py", line 76, in create_project
    p = gl.project.get(project_model_id)
AttributeError: module 'gitlab' has no attribute 'project'

## Specifications

  - python-gitlab version: python-gitlab     2.7.1
  - API version you are using (v3/v4): V4
  - Gitlab server version (or gitlab.com): gitlab-ee-13.9.7-ee.0.el7.x86_64

[main.zip](https://github.com/python-gitlab/python-gitlab/files/6587898/main.zip)

**Comment by JohnVillalovos** [comment] 2021-06-03 01:07
The problem is this line:

```
p = gl.project.get(project_model_id)
```

It is `project` singular. It should be `projects` plural.

**Comment by KameKam** [comment] 2021-06-03 08:20
Hello 
Thanks for your reactivity it's appreciate :). I think I send the version of my code where I tried with project without 's', but in fact I've tried already with s but got same error see below with the fix : 
PS C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab> .\main.py
Start creation of  elk
Sub already exists
applications group exists,go to  elk  application's creation folder
Nothing to do all folder exists
Traceback (most recent call last):
  File "C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab\main.py", line 103, in <module>
    main()
  File "C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab\main.py", line 100, in main
    spoke_id=createee_project(app_id)
  File "C:\Users\ycam\OneDrive - Pierre & Vacances - Centerparcs Group\Desktop\Python-Gitlab\main.py", line 76, in createee_project
    p = gl.projects.get(project_model_id)
AttributeError: module 'gitlab' has no attribute 'projects'

**Comment by benjamb** [comment] 2021-06-03 15:35
@KameKam I think you've confused things by importing gitlab as `gl`, the actual client object you've named `gitl`, so you probably want `gitl.projects.get(project_model_id)`.

**Comment by JohnVillalovos** [comment] 2021-06-03 15:36
@KameKam  

I think the issue is that it should be using the `gitl` object, in your code. As you imported `gitlab as gl`.  So `gl` is the module and is *NOT* a `Gitlab` object.

Usually people do code like this

```
import gitlab  # don't rename it, you aren't going to have to reference it that much.

# gl is the Gitlab object
gl = gitlab.Gitlab.from_config('pvcp', ['./.python-gitlab.cfg'])

gl.projects.get(MY_PROJECT_ID)
```

**Comment by JohnVillalovos** [comment] 2021-06-03 15:42
I'm going to close this again. If what @benjamb  and I said don't fix the issue please re-open.

**Closed by JohnVillalovos** 2021-06-03 15:42 UTC
