### ISSUE TITLE
project.artifact() broken

### ISSUE THREAD

**Issue by aparcar** [python-gitlab/python-gitlab#1091] opened 2020-05-06 18:34 UTC
## Description of the problem, including code/CLI snippet

I'm trying to download artifacts from a project, the example is fairly simple:

```python
project = gl.projects.get(14434387)
project.artifact('master', 'output/rbvf.json.gz', 'rebuild_ramips-mt7620')
```

Token works, project exists, downloading artifacts individually works.

I'm wondering if the gitlab.com API itself is currently broken?

## Expected Behavior

Receive the latest artifacts of a specified job on a specified branch.

## Actual Behavior

```pythontrace
Traceback (most recent call last):
  File "/home/a/src/openwrt/rebuild/.direnv/lib/python3.8/site-packages/gitlab/exceptions.py", line 275, in wrapped_f
    return f(*args, **kwargs)
  File "/home/a/src/openwrt/rebuild/.direnv/lib/python3.8/site-packages/gitlab/v4/objects.py", line 4871, in artifact
    result = self.manager.gitlab.http_get(
  File "/home/a/src/openwrt/rebuild/.direnv/lib/python3.8/site-packages/gitlab/__init__.py", line 598, in http_get
    result = self.http_request(
  File "/home/a/src/openwrt/rebuild/.direnv/lib/python3.8/site-packages/gitlab/__init__.py", line 571, in http_request
    raise GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 404: 404 Not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/a/src/openwrt/rebuild/consumer.py", line 158, in <module>
    gitlab_download()
  File "/home/a/src/openwrt/rebuild/consumer.py", line 149, in gitlab_download
    project.artifact('master', 'output/rbvf.json.gz', 'rebuild_ramips-mt7620', streamed=True, action=store)
  File "/home/a/src/openwrt/rebuild/.direnv/lib/python3.8/site-packages/gitlab/cli.py", line 43, in wrapped_f
    return f(*args, **kwargs)
  File "/home/a/src/openwrt/rebuild/.direnv/lib/python3.8/site-packages/gitlab/exceptions.py", line 277, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabGetError: 404: 404 Not found
```

## Specifications

  - python-gitlab version: python-gitlab==2.2.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by max-wittig** [comment] 2020-05-07 06:14
Looks like a GitLab error to me. Have you tried the same with curl?

**Comment by aparcar** [comment] 2020-05-07 08:41
Is that a expected thing to happen from time to time or should I open an upstream issue?

**Comment by max-wittig** [comment] 2020-05-07 13:16
Not sure. I'm not using this feature. If you reproduced it with curl, please go ahead and create an issue at GitLab or search for an existing one first.

**Comment by max-wittig** [comment] 2020-05-12 10:27
@aparcar Could you find out more? Did it work with curl?

**Comment by rokpu-wish** [comment] 2020-07-15 18:54
So this actually works for me, but when I try 
```
job = project.jobs.get(pipeline_job.id, lazy=True)
job.artifact('job-result.json')
```

I get a 404 page not found. 
But when I do 
```
artifact = project.artifact('master', 'job-result.json', 'run')
```

It works

**Comment by max-wittig** [comment] 2020-10-12 20:39
Closing as info is missing

**Closed by max-wittig** 2020-10-12 20:39 UTC
Labels: need info
