### ISSUE TITLE
create runner failing

### ISSUE THREAD

**Issue by rhyre** [python-gitlab/python-gitlab#310] opened 2017-09-15 11:56 UTC
After update to 1.0 I can't create runner with project.runners.create({'runner_id': 20})

Traceback: 
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gitlab/exceptions.py", line 231, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 171, in create
    return self._obj_cls(self, server_data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/base.py", line 560, in __init__
    self._create_managers()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/base.py", line 591, in _create_managers
    managers = getattr(self, '_managers', None)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/base.py", line 567, in __getattr__
    return self.__dict__['_attrs'][name]
TypeError: list indices must be integers, not str

```

**Comment by gpocentek** [comment] 2017-09-16 09:47
Thank you for your report.

Which API version are you using, v3 or v4?

**Comment by gpocentek** [comment] 2017-09-19 05:00
Looking at the trace you're using v4. I've note been able to reproduce the problem. Could you provide more information about the runner object itself: `gl.runners.get(20).attributes` (remove sensitive information from the output).

**Comment by rhyre** [comment] 2017-09-19 06:41
sorry for the delay, i was on vacation. 
I'm using v4 and gitlab v9.0.5
It wasn't an issue on prev version 0.22 or something. 
output:
gitlab.exceptions.GitlabGetError: 403: 403 Forbidden  - No access granted

**Comment by gpocentek** [comment] 2017-09-21 20:15
The `_attrs` seems to have turned into a list, instead of being a dict. It might be a bug in python-gitlab, but I don't see how this could happen for now.

Could you check the value of `self.__dict__['_attrs']` using pdb, right before the error? This might help.

**Comment by gpocentek** [comment] 2017-10-08 08:08
hi @rhyre, any news on this issue? Did you get a chance to run pdb to get more info?

Thank you.

**Comment by gpocentek** [comment] 2017-11-01 14:18
I'm closing this issue but feel free to reopen if you can provide additional information.

**Closed by gpocentek** 2017-11-01 14:18 UTC
Labels: need info

**Comment by uri** [comment] 2017-11-17 04:34
I had the exact same issue when I was trying to create a project. The problem was I was using `http://gitlab.com` as the base URL. Everything started working when I switched to **https**.

**Comment by blorby** [comment] 2018-01-30 15:52
i'm having the same issue with gl.protectedbranches.create({'name': 'test'})

i'm getting:
`
/usr/local/lib/python2.7/dist-packages/gitlab/base.pyc in __getattr__(self, name)
    583         except KeyError:
    584             try:
--> 585                 value = self.__dict__['_attrs'][name]
    586
    587                 # If the value is a list, we copy it in the _updated_attrs dict

TypeError: list indices must be integers, not str
`

**Comment by mirakulus** [comment] 2018-11-26 15:10
Had the same problem with project.commits.create() when our Gitlab Instance suddenly switched to HTTPS protocol.
Solution: login to API using HTTPS in base url
