### ISSUE TITLE
.play() on job returns 500 even though job is started successfully

### ISSUE THREAD

**Issue by wardbox** [python-gitlab/python-gitlab#2918] opened 2024-07-09 19:36 UTC
## Description of the problem, including code/CLI snippet
I'm starting a job via the API and getting a 400 error even though I can see the job getting kicked off and running in the UI. Because of this I have no way of knowing if the error is reliable.
```
job = project.jobs.get(job.id, lazy=True)
job.play()
```
![image](https://github.com/python-gitlab/python-gitlab/assets/31261302/5fa477bf-9117-4169-bc9c-6b557ae5f57a)

## Expected Behavior
`200 OK - Job played`
Job runs and completes successfully

## Actual Behavior
`400 Bad request - Unplayable Job`
Job runs and completes successfully

## Specifications

  - python-gitlab version: 4.7.0
  - API version you are using (v3/v4):  v4
  - Gitlab server version (or gitlab.com): gitlab.com

**Comment by JohnVillalovos** [comment] 2024-07-09 20:22
Hi,

Can you try:

```
gl.enable_debug()
<your prep work here>
job = project.jobs.get(job.id, lazy=False)
job.pprint()
job.play()
```

And hopefully will have more info on what is going on?

And you are sure that the job isn't already running before you do the play?

**Comment by JohnVillalovos** [comment] 2024-07-09 21:50
Possibly useful: https://gitlab.com/gitlab-org/gitlab/-/issues/276938

Which mentions needing to use: `when: manual` in the job definition.

**Comment by wardbox** [comment] 2024-07-10 00:06
I'll try enabling the debug and getting you the result. I confirmed 100% that the job was not running beforehand and my job does use the `when: manual` setting which is where I actually started on my journey to figure out what's going on!

**Comment by wardbox** [comment] 2024-07-11 01:47
I'm not sure what changed, but it is not failing now.

**Comment by JohnVillalovos** [comment] 2024-07-11 02:33
I'm guessing some issue with Gitlab. python-gitlab is fairly simple in sending the request so I doubt it was the cause of the issue.

I'll go ahead and close this.

**Closed** 2024-07-11 02:33 UTC
Labels: need info

**Comment by nejch** [comment] 2024-07-11 08:45
@JohnVillalovos agreed, especially 500 indicates something on the GitLab side.
