### ISSUE TITLE
attribute shared_with_groups is missing on group

### ISSUE THREAD

**Issue by Michenux** [python-gitlab/python-gitlab#1302] opened 2021-02-16 13:40 UTC
## Description of the problem, including code/CLI snippet

On a group, in the member section, add a share with another group.
Then call the API to retrieve the group, you can see that the attribute shared_with_groups is filled.
```
curl --header "PRIVATE-TOKEN: <your_token>" "https://git.testgaz.com/api/v4/groups/<group_id>"
````

With the gitlab python library, when i load the same group, i have no attribute shared_with_groups inside.

## Specifications

  - python-gitlab version: 3.9
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.8.4

**Comment by nejch** [comment] 2021-05-01 13:11
Hi @Michenux, I can't reproduce this behavior and we have functional tests proving this works, both with share and unshare. See below:
https://github.com/python-gitlab/python-gitlab/blob/1e6305e865d4e586f2fa3a5f638095d0c885e224/tools/functional/api/test_groups.py#L45-L55

Perhaps you were calling `get()` the second time with `lazy=True` and the second API call was never made?

In any case, have a look at the code in the tests to see how it should be done. I'll close this but If you still have any issues later please feel free to re-open it ;)

**Closed by nejch** 2021-05-01 13:11 UTC
