### ISSUE TITLE
Different result of same function.

### ISSUE THREAD

**Issue by DolajoCZ** [python-gitlab/python-gitlab#1532] opened 2021-06-23 09:23 UTC
## Description of the problem, including code/CLI snippet
Different result of same function.

```python
gl_client = gitlab.Gitlab(GITLAB_URL, GITLAB_API_KEY, ssl_verify=False)

gl_client.projects.get(10).branches.list(all=True)  # return list of length 36
gl_client.projects.get(10).branches.list(all=True)  # return list of length 20
```

## Expected Behavior
Return same number of records after recall of function. In this case 36.

## Actual Behavior
For first call of function I get 36 records and for second call of same function I get 20 records.

## Specifications

  - python-gitlab version: 2.7.1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): GitLab Community Edition 13.12.3

**Comment by nejch** [comment] 2021-06-23 10:36
I can reproduce this if I make two calls in short succession. If I give it enough time between the two calls, it returns all pages. 

But I can also reproduce this with curl, so this seems to me an upstream/server rate-limiting thing: if you enable debug info with `gl_client.enable_debug()` you'll see that on your second call, the GitLab server response is missing the `link` and associated pagination headers.

**Comment by nejch** [comment] 2021-06-23 11:37
Found the upstream issue, seems to be a branch endpoint specific issue: https://gitlab.com/gitlab-org/gitlab/-/issues/331297

So I'm closing this as there's not much we can do here. I suggest you introduce a wait to ensure you get the headers if needed.

**Closed by nejch** 2021-06-23 11:37 UTC
Labels: upstream
