### ISSUE TITLE
How to change the default port number?

### ISSUE THREAD

**Issue by lyenliang** [python-gitlab/python-gitlab#781] opened 2019-05-27 03:47 UTC
## Description of the problem, including code/CLI snippet
When I run the following script, I got an error message saying `requests.exceptions.ConnectionError: HTTPConnectionPool(host='my-gitlab.com', port=80): Max retries exceeded with url: /api/v4/projects?membership=false&order_by=created_at&owned=false&page=2&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107784be0>: Failed to establish a new connection: [Errno 61] Connection refused',))`

```
# file name: poc.py
import gitlab

gl = gitlab.Gitlab(
    'http://my-gitlab.com:10080', 
    private_token='<my_private_token>'
    )
projects = gl.projects.list(all=True)
for project in projects:
    print(project.attributes['name'])
```
I think the error occurs because the port is not set to `10080`. The API uses the default port 80 to communicate with the gitlab server.

## Expected Behavior

The code should be able to list all the projects on `my-gitlab.com:10080`.

## Actual Behavior

The code generates an error message saying `requests.exceptions.ConnectionError: HTTPConnectionPool(host='my-gitlab.com', port=80): Max retries exceeded with url: /api/v4/projects?membership=false&order_by=created_at&owned=false&page=2&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107784be0>: Failed to establish a new connection: [Errno 61] Connection refused',))`

## Specifications

  - python-gitlab version: 1.8.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 11.10.0

**Comment by lyenliang** [comment] 2019-05-27 06:06
`python-gitlab` tried to use port 80 to communicate with gitlab server because there was an `IndexError` triggered at line 825 of gitlab/init.py. 

I've checked that the length of `self._data` is 20. And I don't know why `self._current` was added to 20. `self._data[20]` triggers IndexError because the index's maximum value is 19.

Is `len(self._data) == 20` an expected behavior?

**Comment by lyenliang** [comment] 2019-05-27 07:29
The [`result`](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/__init__.py#L759) returned by `self._gl.http_request("get", url, query_data=query_data, **kwargs)` doesn't contain port number 10080. 
Is this a bug or a normal behavior?

**Comment by gpocentek** [comment] 2019-05-27 07:32
Hi,

This is a bug in Gitlab. The server doesn't return the correct port in the Links headers. We rely on these headers to make additional requests when using pagination. See #745.

**Comment by gpocentek** [comment] 2019-05-27 07:39
Additional info, it has been fixed in Gitlab and is available in Gitlab 11.9: https://gitlab.com/gitlab-org/gitlab-ce/issues/57684

**Closed by gpocentek** 2019-05-27 07:39 UTC

**Comment by lyenliang** [comment] 2019-05-27 07:53
I'm using gitlab 11.10.0. Probably this bug is reopened in 11.10.0.

**Comment by deckar01** [comment] 2019-05-28 15:52
I am able to reproduce this bug on GitLab 11.10.4 using python-gitlab 1.8.0. Initial requests with the server URL from my config succeed, then pagination requests returned from the GitLab instance fail due to the port number changing to 80.

**Comment by deckar01** [comment] 2019-05-28 16:34
I am currently hacking around this with the following snippet:

```py
def list_all(target, *args, **kwargs):
    page = 1
    while True:
        items = target.list(*args, **kwargs, page=page)
        if not items:
            break
        page += 1
        for item in items:
            yield item
```

```py
# Usage
issues = list_all(project.issues, state='opened')
    for issue in issues:
        ...
```

**Comment by PavelGloba** [comment] 2019-07-12 15:14
Ran into similar issue
@gpocentek Is there a particular reason why the 'Link' header is used instead of given url + headers mentioned bellow?
`
X-Next-Page: 3
X-Page: 2
X-Per-Page: 10
X-Prev-Page: 1
X-Total-Pages: 7
`
