### ISSUE TITLE
Cannot change main email of ldap-account

### ISSUE THREAD

**Issue by martingabelmann** [python-gitlab/python-gitlab#1137] opened 2020-07-13 15:09 UTC
## Description of the problem, including code/CLI snippet
Very similar behaviour to #336 i.e. changing the users `email` attribute and calling `save()` does not have any effect.

## Expected Behavior
The email of the user should be changed to the value of the `email` attribute.

## Actual Behavior
No changes were applied.
Edit: I also do not receive a confirmation email or the-like. Outgoing emails (e.g. notifications) are working.

## Specifications

  - python-gitlab version: 2.4.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 13.1.3 (8411f47246f)

I'm trying to modify an ldap-associated account (gitlab ce) could this be the problem? - Adding secondary emails works, though.

**Comment by max-wittig** [comment] 2020-07-13 15:19
As far as I know, GitLab CE doesn't have LDAP support. That's an EE feature. Are you sure that you have GitLab CE?

**Comment by martingabelmann** [comment] 2020-07-13 17:21
According to [this](https://docs.gitlab.com/ce/administration/auth/ldap/]) also ce does support "read-only" ldap authentification.  
Gitlab (ce) seems to read the ldap `mail` attribute only on the first login and then never changes it.   
In our setup, ldap users are (of course) not allowed to change emails on their own.  
However, from time to time we get requests to change emails which we solved using python-gitlab.  

This also worked for quite some time pretty well. I [implemented](https://github.com/particleKIT/ldapKIT/blob/master/ldapKIT/particleldapchangemail.py#L104) this already in 2017 of course with an earlier version of the gitlab API. Since then, the mail-change feature was only barely used so I can't really tell when it started to stop working :/

**Comment by CoreySmithRing** [comment] 2021-04-23 18:11
Im not sure if this is the same issue but I am also unable to update a SAML user primary email. 
Example of what I tried: 
`              user.email = new_email
                user.skip_reconfirmation = True
                user.save()
`

No errors are presented on the save but no changes are made. I can confirm I can update other attributes I am unable to make updates to the email field.

**Comment by CoreySmithRing** [comment] 2021-04-23 18:51
I did some more digging and this looks like its a gitlab issue. I can perform the same action using the gitlab api directly and still does not update the users nor does it yield an error. I suspect the sdk logic is fine but this is an issue in gitlab.

**Comment by nejch** [comment] 2022-11-16 20:58
I'm going to close this as I think it's a GitLab issue (or intended behavior if re-confirmation is required), especially if other attributes can be updated normally. The client in the end really only sends the parameters in the POST body.

If future readers come across this and can reproduce this only with python-gitlab and not with curl for example, then we can revisit this.

**Closed by nejch** 2022-11-16 20:58 UTC
Labels: upstream
